### ISSUE TITLE
hyprland-share-picker fails to build with Clang

### ISSUE THREAD

**Issue by jbeich** [hyprwm/xdg-desktop-portal-hyprland#22]
Regressed by 27118ee3d71b
```c++
$ export CC=clang CXX=clang++
$ cmake -G Ninja -S hyprland-share-picker -B /tmp/hyprland-share-picker_build
$ cmake --build /tmp/hyprland-share-picker_build
[...]
hyprland-share-picker/main.cpp:64:51: error: non-constant-expression cannot be narrowed from type 'long long' to 'unsigned long' in initializer list [-Wc++11-narrowing]
            result.push_back({TITLESTR, CLASSSTR, std::stoll(IDSTR)});
                                                  ^~~~~~~~~~~~~~~~~
hyprland-share-picker/main.cpp:64:51: note: insert an explicit cast to silence this issue
            result.push_back({TITLESTR, CLASSSTR, std::stoll(IDSTR)});
                                                  ^~~~~~~~~~~~~~~~~
                                                  static_cast<unsigned long>( )
1 error generated.
```

**Comment by vaxerski** [comment]
haha clang deez nuts

a9b76c7f997daffa0fababdb54e5feb2ee05fdc1
