### ISSUE TITLE
Fails to build on 32-bit architectures (e.g., armv7, i386, powerpc)

### ISSUE THREAD

**Issue by jbeich** [hyprwm/xdg-desktop-portal-hyprland#190]
Regressed by c5b69eb5b5f0. See also https://github.com/hyprwm/hyprlang/issues/8

```c++
$ export CXXFLAGS=-m32
$ cmake -G Ninja -B /tmp/xdph_build
$ cmake --build /tmp/xdph_build 
[...]
src/core/PortalManager.cpp:213:71: error: call to constructor of 'const CConfigValue &' is ambiguous
    m_sConfig.config->addConfigValue("general:toplevel_dynamic_bind", {0L});
                                                                      ^~~~
/usr/include/hyprlang.hpp:192:9: note: candidate constructor
        CConfigValue(const INT value);
        ^
/usr/include/hyprlang.hpp:193:9: note: candidate constructor
        CConfigValue(const FLOAT value);
        ^
/usr/include/hyprlang.hpp:194:9: note: candidate constructor
        CConfigValue(const STRING value);
        ^
/usr/include/hyprlang.hpp:289:67: note: passing argument to parameter 'value' here
        void addConfigValue(const char* name, const CConfigValue& value);
                                                                  ^
1 error generated.
```

**Comment by vaxerski** [comment]
should be done with above
